Bugfix. Everytime I tried to access any URL in Django, I was receiving the error below. This method clear() from list was introduced in Python 3.3. After replacing clear() with other syntax, the problem was solved.
Traceback (most recent call last):
  File "/home/locus/.virtualenvs/agfutebol/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/locus/.virtualenvs/agfutebol/local/lib/python2.7/site-packages/django_aws_xray/middleware.py", line 28, in __call__
    trace.send()
  File "/home/locus/.virtualenvs/agfutebol/local/lib/python2.7/site-packages/django_aws_xray/xray.py", line 36, in send
    self._segment_buffer.clear()
AttributeError: 'list' object has no attribute 'clear'